export enum ListingSource {
  crea = "crea",
  kvcore = "kvcore",
}

export enum AreaUnitType {
  sm = "square meters",
  sf = "square feet",
  acres = "acres",
}

export interface IListing {
  _id: string
  source: ListingSource
  source_id: string
  ArchitecturalStyle?: string
  AssociationFee?: string
  AssociationFeeFrequency?: string
  AttachedGarageYN: boolean
  BathroomsHalf?: number
  BathroomsTotal?: number
  BedroomsTotal?: number
  BuildingAreaTotal?: number
  BuildingAreaUnits?: AreaUnitType
  CarportSpaces?: string
  CarportYN: boolean
  City: string
  CoListAgentCellPhone?: string
  CoListAgentDesignation?: string
  CoListAgentDirectPhone?: string
  CoListAgentEmail?: boolean
  CoListAgentFax?: string
  CoListAgentFullName?: string
  CoListAgentKey?: string
  CoListAgentOfficePhone?: string
  CoListAgentOfficePhoneExt?: string
  CoListAgentPager?: string
  CoListAgentTollFreePhone?: string
  CoListAgentURL?: string
  CoListOfficeFax?: string
  CoListOfficeKey?: string
  CoListOfficeName?: string
  CoListOfficePhone?: string
  CoListOfficePhoneExt?: string
  CoListOfficeURL?: string
  CommunityFeatures?: string
  ConstructionMaterials?: string
  Cooling?: string
  CoolingYN: boolean
  Country: string
  CoveredSpaces?: string
  Fencing?: string
  FireplaceFeatures?: string
  FireplaceFuel?: string
  FireplacesTotal?: string
  Flooring?: string
  FrontageLength?: string
  FrontageType?: string
  GarageSpaces?: string
  GarageYN: boolean
  GreenBuildingCertification?: string
  GreenCertificationRating?: string
  Heating?: string
  HeatingFuel?: string
  Latitude?: string
  Lease?: string
  LeaseFrequency?: string
  LeaseTerm?: string
  Levels?: number
  ListAOR?: string
  ListAgentCellPhone?: string
  ListAgentDesignation?: string
  ListAgentDirectPhone?: string
  ListAgentEmail: boolean
  ListAgentFax?: string
  ListAgentFullName?: string
  ListAgentKey?: string
  ListAgentOfficePhone?: string
  ListAgentOfficePhoneExt?: string
  ListAgentPager?: string
  ListAgentURL?: string
  ListOfficeFax?: string
  ListOfficeKey?: string
  ListOfficeName?: string
  ListOfficePhone?: string
  ListOfficePhoneExt?: string
  ListOfficeURL?: string
  ListPrice?: number
  ListingContractDate?: string
  ListingId?: string
  ListingKey?: string
  Longitude?: number
  LotFeatures?: string
  LotSizeArea?: number
  LotSizeUnits?: string
  ModificationTimestamp?: string
  MoreInformationLink?: string
  NumberOfUnitsTotal?: number
  OpenParkingSpaces?: string
  OpenParkingYN: boolean
  OriginatingSystemKey?: string
  OriginatingSystemName?: string
  OwnershipType?: string
  ParkingTotal?: number
  PhotosChangeTimestamp: string
  PhotosCount: number
  PoolFeatures?: string
  PoolYN: boolean
  PostalCode?: string
  PropertyType?: string
  PublicRemarks?: string
  Roof?: string
  RoomDimensions1?: string
  RoomDimensions10?: string
  RoomDimensions11?: string
  RoomDimensions12?: string
  RoomDimensions13?: string
  RoomDimensions14?: string
  RoomDimensions15?: string
  RoomDimensions16?: string
  RoomDimensions17?: string
  RoomDimensions18?: string
  RoomDimensions19?: string
  RoomDimensions2?: string
  RoomDimensions20?: string
  RoomDimensions3?: string
  RoomDimensions4?: string
  RoomDimensions5?: string
  RoomDimensions6?: string
  RoomDimensions7?: string
  RoomDimensions8?: string
  RoomDimensions9?: string
  RoomLength1?: string
  RoomLength10?: string
  RoomLength11?: string
  RoomLength12?: string
  RoomLength13?: string
  RoomLength14?: string
  RoomLength15?: string
  RoomLength16?: string
  RoomLength17?: string
  RoomLength18?: string
  RoomLength19?: string
  RoomLength2?: string
  RoomLength20?: string
  RoomLength3?: string
  RoomLength4?: string
  RoomLength5?: string
  RoomLength6?: string
  RoomLength7?: string
  RoomLength8?: string
  RoomLength9?: string
  RoomLengthWidthUnits1?: string
  RoomLengthWidthUnits10?: string
  RoomLengthWidthUnits11?: string
  RoomLengthWidthUnits12?: string
  RoomLengthWidthUnits13?: string
  RoomLengthWidthUnits14?: string
  RoomLengthWidthUnits15?: string
  RoomLengthWidthUnits16?: string
  RoomLengthWidthUnits17?: string
  RoomLengthWidthUnits18?: string
  RoomLengthWidthUnits19?: string
  RoomLengthWidthUnits2?: string
  RoomLengthWidthUnits20?: string
  RoomLengthWidthUnits3?: string
  RoomLengthWidthUnits4?: string
  RoomLengthWidthUnits5?: string
  RoomLengthWidthUnits6?: string
  RoomLengthWidthUnits7?: string
  RoomLengthWidthUnits8?: string
  RoomLengthWidthUnits9?: string
  RoomLevel1?: string
  RoomLevel10?: string
  RoomLevel11?: string
  RoomLevel12?: string
  RoomLevel13?: string
  RoomLevel14?: string
  RoomLevel15?: string
  RoomLevel16?: string
  RoomLevel17?: string
  RoomLevel18?: string
  RoomLevel19?: string
  RoomLevel2?: string
  RoomLevel20?: string
  RoomLevel3?: string
  RoomLevel4?: string
  RoomLevel5?: string
  RoomLevel6?: string
  RoomLevel7?: string
  RoomLevel8?: string
  RoomLevel9?: string
  RoomType1?: string
  RoomType10?: string
  RoomType11?: string
  RoomType12?: string
  RoomType13?: string
  RoomType14?: string
  RoomType15?: string
  RoomType16?: string
  RoomType17?: string
  RoomType18?: string
  RoomType19?: string
  RoomType2?: string
  RoomType20?: string
  RoomType3?: string
  RoomType4?: string
  RoomType5?: string
  RoomType6?: string
  RoomType7?: string
  RoomType8?: string
  RoomType9?: string
  RoomWidth1?: string
  RoomWidth10?: string
  RoomWidth11?: string
  RoomWidth12?: string
  RoomWidth13?: string
  RoomWidth14?: string
  RoomWidth15?: string
  RoomWidth16?: string
  RoomWidth17?: string
  RoomWidth18?: string
  RoomWidth19?: string
  RoomWidth2?: string
  RoomWidth20?: string
  RoomWidth3?: string
  RoomWidth4?: string
  RoomWidth5?: string
  RoomWidth6?: string
  RoomWidth7?: string
  RoomWidth8?: string
  RoomWidth9?: string
  Sewer?: string
  SocialMediaWebsite?: string
  StateOrProvince: string
  Stories?: number
  StreetAdditionalInfo?: string
  StreetDirPrefix?: string
  StreetDirSuffix?: string
  StreetName?: string
  StreetNumber?: string
  StreetSuffix?: string
  SubdivisionName?: string
  UnitNumber?: number
  UnparsedAddress: string
  View?: string
  ViewYN: boolean
  WaterBodyName?: string
  WaterfrontYN: boolean
  YearBuilt?: number
  Zoning?: string
  deleted: boolean
  location: {
    type: "Point"
    coordinates: number[]
  }
  photos: [
    {
      sourceId: string
      order: number
      url: string
      modificationTimestamp: string
    },
  ]
  timestamp: number
}
