export interface IListing {
  _id: string
  VIVA_YoungestAgeAllowed: number
  StreetDirPrefix: string
  VIVA_SubdividableAreaMax: string
  LivingAreaUnits: string
  TaxLegalDescription: string
  LockBoxLocation: string
  YearEstablished: number
  VIVA_CoBuyerAgent2MlsId: string
  LaundryFeatures: string[]
  Flooring: string[]
  PhotosCount: number
  FireplacesTotal: number
  VIVA_ValueFixedEquipment: string
  WaterfrontFeatures: string[]
  CoBuyerAgentDirectPhone: string
  ViewYN: boolean
  SeniorCommunityYN: boolean
  Cooling: string[]
  ExteriorFeatures: string[]
  VIVA_LeaseYearsRemaining: string
  StatusChangeTimestamp: string
  VIVA_Bath2PieceTotal: number
  BuyerAgentFullName: string
  VIVA_Ensuite3PieceTotal: number
  VIVA_TaxJurisdiction: string
  VIVA_BathroomsCountThirdLevel: number
  VIVA_CoListAgent2DirectPhone: string
  VIVA_BedroomsCountLowerLevel: number
  CancelationDate: string
  BuildingName: string
  AssociationFeeFrequency: string
  VIVA_CoBuyerOffice2Name: string
  OccupantPhone: string
  VIVA_Bath4PieceTotal: number
  HeatingYN: boolean
  VIVA_BuyerAgentNationalAssociationId: string
  VIVA_StrataLotIncludes: string[]
  VIVA_PurchaseContractTimestamp: string
  VIVA_LegalNonConformingYN: boolean
  AboveGradeFinishedArea: string
  ListingKeyNumeric: string
  MajorChangeType: string
  VIVA_YoungestAgeAllowedNotes: string
  Appliances: string[]
  VIVA_ParkingStrataCommonSpaces: number
  MLSAreaMajor: string
  TaxAnnualAmount: number
  VIVA_BathroomsCountLowerLevel: number
  VIVA_CoListOffice2Phone: string
  VIVA_CoBuyerOfficeNationalAssociationId: string
  VIVA_LivingAreaSecond: number
  VIVA_FinancingNotes: string
  OriginatingSystemKey: string
  CountyOrParish: string
  PropertyType: string
  BathroomsTotalDecimal: number
  OriginatingSystemName: string
  AssociationYN: boolean
  MlsStatus: string
  VIVA_ParkingAreaStrata: string
  StreetNumber: string
  LeaseTerm: string
  ListingKey: string
  VIVA_SmokingBylaw: string
  VIVA_LivingAreaAuxBldg: string
  VIVA_CoBuyerOffice2NationalAssociationId: string
  ListAgentKeyNumeric: string
  VIVA_CommercialListingType: string[]
  VIVA_CoListAgent2AOR: string
  StreetDirSuffix: string
  CoBuyerOfficePhone: string
  CoListOfficePhoneExt: string
  VIVA_LivingAreaLower: number
  Directions: string
  VIVA_SalesBrochureURL: string
  AttachedGarageYN: boolean
  StandardStatus: string
  VIVA_LivingAreaMain: number
  Roof: string[]
  VIVA_CoBuyerOffice2MlsId: string
  ParkingTotal: number
  ListAgentOfficePhone: string
  CoListOfficeKeyNumeric: string
  VIVA_ValueGoodwill: string
  VIVA_LivingAreaOther: number
  VIVA_VirtualTour2URLBranded: string
  ListingTerms: string[]
  VIVA_UnfinishedAreaTotal: string
  VIVA_Restrictions: string[]
  PropertySubType: string
  BuyerAgentDirectPhone: string
  Possession: string[]
  VIVA_CoBuyerOffice2KeyNumeric: string
  CoListAgentOfficePhone: string
  BathroomsFull: string
  WaterfrontYN: boolean
  LotSizeAcres: number
  SubdivisionName: string
  BuyerOfficeAOR: string
  InternetAddressDisplayYN: boolean
  WithdrawnDate: string
  VIVA_CoListAgentNationalAssociationId: string
  VIVA_CommercialArea: string
  WaterSource: string[]
  VIVA_StrataPlanType: string
  VIVA_LeaseAmountAdditional: string
  DoorFeatures: string[]
  StoriesTotal: number
  VIVA_KitchensCountSecondLevel: string
  YearBuilt: string
  ElectricOnPropertyYN: boolean
  VIVA_ClosePriceLeaseTotal: number
  VIVA_Owner2Phone: string
  VIVA_CoListOfficeNationalAssociationId: string
  VIVA_ForeignListingId: string
  VIVA_SubdividableAreaMin: string
  ZoningDescription: string
  VIVA_BedroomsCountOtherLevel: number
  PreviousListPrice: number
  PetsAllowed: string[]
  DaysOnMarket: number
  VIVA_CoBuyerAgent2FullName: string
  BuyerAgencyCompensationType: string
  NetOperatingIncome: string
  OccupantType: string
  OtherStructures: string[]
  AssociationAmenities: string[]
  BodyType: string[]
  ClosePrice: number
  VirtualTourURLZillow: string
  VIVA_ListOfficeNationalAssociationId: string
  StreetNumberNumeric: number
  VIVA_FeatureSheetURL: string
  LivingArea: number
  TaxAssessedValue: number
  CoListAgentKeyNumeric: number
  VIVA_OperatingExpensePerSqft: string
  ParkingFeatures: string[]
  PostalCodePlus4: string
  BuyerOfficePhoneExt: string
  NumberOfUnitsInCommunity: number
  Heating: string[]
  BuildingAreaSource: string
  CoListAgentMlsId: string
  VIVA_ParkingStrataLCPSpaces: number
  BuyerOfficePhone: string
  VIVA_BedroomsCountSecondLevel: number
  VIVA_Chattels: string
  CoListOfficeEmail: string
  ListingId: string
  VIVA_MHRNumber: string
  VIVA_OriginatingSystemTimestamp: number
  BathroomsTotalInteger: number
  VIVA_KitchensCountOtherLevel: number
  VIVA_NumberOfUnitsInBuilding: number
  VIVA_CoListOffice2KeyNumeric: string
  VIVA_PossessionNotes: string
  BuildingAreaUnits: string
  VIVA_BuildingAreaUnfinished: number
  OwnerPhone: string
  City: string
  VIVA_CoBuyerAgent2AOR: string
  InternetEntireListingDisplayYN: boolean
  BuyerAgentOfficePhone: string
  BuyerAgencyCompensation: string
  CoBuyerOfficeKeyNumeric: string
  LeaseExpiration: string
  InternetAutomatedValuationDisplayYN: boolean
  VIVA_PropertyManagerPhone: string
  VIVA_DepreciationReportYN: boolean
  VIVA_CoListAgent2Email: string
  TaxYear: number
  VIVA_AgentInformation: string[]
  VIVA_BuyerOrigin: string
  DirectionFaces: string
  VIVA_BedAndBreakfast: string
  VIVA_MlsMajorChangeType: string
  ConstructionMaterials: string[]
  VIVA_BuildingLevelType: string
  ListingInputOriginalMedia: string
  OccupantName: string
  VIVA_BBQsAllowedNotes: string
  PrivateRemarks: string
  InternetConsumerCommentYN: boolean
  BuildingAreaTotal: number
  YearBuiltSource: string
  VIVA_CoListAgent2FullName: string
  OtherEquipment: string[]
  VIVA_CoListAgent2MlsId: string
  BedroomsTotal: number
  ShowingInstructions: string
  VIVA_BuyerOfficeNationalAssociationId: string
  CoListAgentDirectPhone: string
  VIVA_AssociationFeeYear: number
  VIVA_Bath3PieceTotal: number
  CoolingYN: boolean
  CarportSpaces: number
  LotSizeUnits: string
  ListAgentEmail: string
  VIVA_BedroomsOrDensTotal: number
  MajorChangeTimestamp: string
  LeaseAmountFrequency: string
  VIVA_LivingAreaMainBldg: string
  CoBuyerAgentEmail: string
  VIVA_Ensuite2PieceTotal: number
  VIVA_CoBuyerAgent2KeyNumeric: string
  GarageYN: boolean
  VIVA_DrivewayYN: boolean
  VIVA_AdditionalAccommodation: string
  VIVA_BathroomsCountSecondLevel: number
  Longitude: number
  CarportYN: boolean
  PublicRemarks: string
  VIVA_CoListOffice2AOR: string
  VIVA_KitchensCountThirdLevel: number
  VIVA_BalconyAreaStrata: string
  CoListOfficeName: string
  PurchaseContractDate: string
  RoadSurfaceType: string[]
  PriceChangeTimestamp: string
  LeasableArea: string
  ListingContractDate: string
  MLSAreaMinor: string
  Zoning: string
  ListAgentAOR: string
  CoBuyerAgentKeyNumeric: string
  VIVA_SoundBiteURL: string
  VIVA_KitchensCountLowerLevel: number
  LivingAreaSource: string
  ListAOR: string
  VIVA_PatioAreaStrata: string
  VIVA_LeasedEquipment: string[]
  ListOfficeName: string
  CoBuyerOfficeName: string
  BelowGradeFinishedArea: string
  Basement: string[]
  BusinessType: string[]
  VIVA_LeaseHeldBy: string
  Latitude: number
  PhotosChangeTimestamp: string
  VIVA_AdditionalPhotosURL: string
  ListPrice: number
  BuyerAgentKeyNumeric: string
  RoadFrontageType: string[]
  ListOfficePhone: string
  VIVA_LotAreaStrataLCP: string
  DOH1: string
  BelowGradeFinishedAreaSource: string
  CoListOfficeMlsId: string
  VIVA_LotShape: string
  VIVA_ProjectedCloseDate: string
  CoBuyerOfficePhoneExt: string
  VIVA_CoListOffice2Name: string
  VIVA_CurrentPrice: number
  StateOrProvince: string
  AboveGradeFinishedAreaUnits: string
  ListOfficeAOR: string
  VIVA_BasementHeightFeet: string
  CoveredSpaces: string
  AssociationFeeIncludes: string[]
  SyndicateTo: string[]
  VirtualTourURLUnbranded: string
  VIVA_CoListAgent2KeyNumeric: string
  CoListAgentEmail: string
  ListOfficeKeyNumeric: string
  VIVA_Bath5PieceTotal: number
  CoListOfficeAOR: string
  FireplaceYN: boolean
  BridgeModificationTimestamp: string
  VIVA_CoBuyerAgent2NationalAssociationId: string
  ListAgentFullName: string
  TaxBookNumber: string
  VIVA_Ensuite4PieceTotal: number
  MainLevelBathrooms: number
  VIVA_CoListOffice2MlsId: string
  PropertyCondition: string[]
  VIVA_CoBuyerAgent2Email: string
  Stories: string
  GrossIncome: string
  ParcelNumber: string
  CoBuyerAgentAOR: string
  FoundationDetails: string[]
  VIVA_OfferAcceptanceDate: string
  View: string[]
  OperatingExpense: string
  SignOnPropertyYN: boolean
  LeaseRenewalOptionYN: boolean
  VIVA_CeilingHeight: string
  VIVA_CoBuyerAgent2DirectPhone: string
  HomeWarrantyYN: boolean
  Levels: string[]
  IDXParticipationYN: boolean
  InteriorFeatures: string[]
  OffMarketDate: string
  CoBuyerAgentMlsId: string
  VIVA_AdditionalRentSqFt: string
  VIVA_Owner2Name: string
  VIVA_RentalAllowed: string
  CloseDate: string
  StreetSuffix: string
  ListAgentMlsId: string
  ListOfficePhoneExt: string
  VIVA_ListPriceIncludesGSTYN: boolean
  VIVA_RentalAllowedNotes: string
  LotSizeDimensions: string
  VIVA_ClosePriceIncludesGSTYN: boolean
  ModificationTimestamp: string
  VIVA_PropertyManager: string
  PropertyAttachedYN: boolean
  VIVA_StorageAreaStrata: string
  BusinessName: string
  BuyerAgentEmail: string
  VIVA_LegacyListingId: string
  Coordinates: number[]
  AccessCode: string
  CoBuyerOfficeMlsId: string
  OriginatingSystemID: string
  VIVA_BedroomsCountThirdLevel: number
  Country: string
  UnitNumber: string
  VIVA_ValueInventory: string
  OpenParkingYN: boolean
  VIVA_BasementHeightInches: number
  LeasableAreaUnits: string
  CoBuyerOfficeAOR: string
  VIVA_LivingAreaThird: number
  ListOfficeMlsId: string
  Inclusions: string
  ListAgentDirectPhone: string
  VirtualTourURLBranded: string
  VIVA_KitchensTotal: number
  CoListAgentFullName: string
  BelowGradeFinishedAreaUnits: string
  VIVA_RoomCount: number
  EntryLocation: string
  ShowingContactPhone: string
  ExistingLeaseType: string[]
  BathroomsHalf: number
  VIVA_CoBuyerOffice2Phone: number
  VIVA_ParkingStrataLotSpaces: number
  VIVA_RoomUnfinishedCount: number
  VIVA_ListAgentNationalAssociationId: string
  VIVA_BBQsAllowedYN: boolean
  LotSizeArea: number
  VIVA_CoListOffice2NationalAssociationId: string
  VIVA_TaxAssessedYear: number
  Sewer: string[]
  ExpirationDate: string
  SyndicationRemarks: string
  VIVA_CoBuyerAgentNationalAssociationId: string
  StreetName: string
  AboveGradeFinishedAreaSource: string
  VIVA_CoListAgent2NationalAssociationId: string
  MainLevelBedrooms: number
  Utilities: string[]
  VIVA_Layout: string
  FireplaceFeatures: string[]
  WindowFeatures: string[]
  NewConstructionYN: boolean
  BuyerAgentAOR: string
  NumberOfBuildings: number
  GarageSpaces: number
  OriginalListPrice: number
  Media: [
    {
      Order: string
      MediaKey: string
      MediaURL: string
      ResourceRecordKey: string
      ResourceName: string
      ClassName: string
      MediaCategory: string
      MimeType: string
      MediaObjectID: string
      ShortDescription: string
    },
  ]
  RentIncludes: string[]
  VIVA_BathroomsCountOtherLevel: number
  BuyerOfficeKeyNumeric: string
  AccessibilityFeatures: string[]
  BuildingFeatures: string[]
  OriginalEntryTimestamp: string
  SourceSystemKey: string
  Ownership: string
  BuyerAgentMlsId: string
  OwnerName: string
  Exclusions: string
  VIVA_SubdividableArea: string
  LotFeatures: string[]
  PostalCode: string
  BuyerOfficeMlsId: string
  VIVA_CoBuyerOffice2AOR: string
  VIVA_BuildingAreaPotential: string
  VIVA_PetsAllowedNotes: string
  NumberOfUnitsTotal: string
  BuyerOfficeName: string
  AssociationFee: number
  LeaseAmount: number
  LotSizeSquareFeet: number
  VIVA_SmokingBylawNotes: string
  CoBuyerAgentFullName: string
  ArchitecturalStyle: string[]
  VIVA_KitchensCountMainLevel: number
  UnparsedAddress: string
  CoListOfficePhone: string
  CoListAgentAOR: string
  FeedTypes: string[]
  url: string
}
